// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "OrderService/internal/dto"
	context "context"

	errs "github.com/erdedan1/shared/errs"

	mock "github.com/stretchr/testify/mock"
)

// MarketService is an autogenerated mock type for the MarketService type
type MarketService struct {
	mock.Mock
}

// ViewMarketsByRoles provides a mock function with given fields: ctx, request
func (_m *MarketService) ViewMarketsByRoles(ctx context.Context, request *dto.ViewMarketsRequest) ([]dto.ViewMarketsResponse, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ViewMarketsByRoles")
	}

	var r0 []dto.ViewMarketsResponse
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ViewMarketsRequest) ([]dto.ViewMarketsResponse, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ViewMarketsRequest) []dto.ViewMarketsResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ViewMarketsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ViewMarketsRequest) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// NewMarketService creates a new instance of MarketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketService {
	mock := &MarketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
