// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "OrderService/internal/dto"
	context "context"

	errs "github.com/erdedan1/shared/errs"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MarketCacheRepo is an autogenerated mock type for the MarketCacheRepo type
type MarketCacheRepo struct {
	mock.Mock
}

// Del provides a mock function with given fields: ctx, key
func (_m *MarketCacheRepo) Del(ctx context.Context, key string) *errs.CustomError {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, string) *errs.CustomError); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errs.CustomError)
		}
	}

	return r0
}

// Get provides a mock function with given fields: ctx, key
func (_m *MarketCacheRepo) Get(ctx context.Context, key string) ([]dto.ViewMarketsResponse, *errs.CustomError) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []dto.ViewMarketsResponse
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dto.ViewMarketsResponse, *errs.CustomError)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dto.ViewMarketsResponse); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ViewMarketsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *errs.CustomError); ok {
		r1 = rf(ctx, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MarketCacheRepo) Set(ctx context.Context, key string, value []dto.ViewMarketsResponse, ttl time.Duration) *errs.CustomError {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, string, []dto.ViewMarketsResponse, time.Duration) *errs.CustomError); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errs.CustomError)
		}
	}

	return r0
}

// NewMarketCacheRepo creates a new instance of MarketCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketCacheRepo {
	mock := &MarketCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
