// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "OrderService/internal/dto"
	context "context"

	errs "github.com/erdedan1/shared/errs"

	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, request
func (_m *OrderService) CreateOrder(ctx context.Context, request *dto.CreateOrderRequest) (*dto.CreateOrderResponse, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *dto.CreateOrderResponse
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderRequest) (*dto.CreateOrderResponse, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderRequest) *dto.CreateOrderResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateOrderRequest) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// GetOrderStatus provides a mock function with given fields: ctx, request
func (_m *OrderService) GetOrderStatus(ctx context.Context, request *dto.GetOrderStatusRequest) (*dto.GetOrderStatusResponse, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 *dto.GetOrderStatusResponse
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrderStatusRequest) (*dto.GetOrderStatusResponse, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrderStatusRequest) *dto.GetOrderStatusResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetOrderStatusRequest) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// SubscribeOrderStatus provides a mock function with given fields: ctx, request
func (_m *OrderService) SubscribeOrderStatus(ctx context.Context, request *dto.GetOrderStatusRequest) (<-chan *dto.GetOrderStatusResponse, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOrderStatus")
	}

	var r0 <-chan *dto.GetOrderStatusResponse
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrderStatusRequest) (<-chan *dto.GetOrderStatusResponse, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrderStatusRequest) <-chan *dto.GetOrderStatusResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *dto.GetOrderStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetOrderStatusRequest) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
