// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	errs "github.com/erdedan1/shared/errs"
	mock "github.com/stretchr/testify/mock"

	model "OrderService/internal/model"

	uuid "github.com/google/uuid"
)

// OrderStatusSubscriber is an autogenerated mock type for the OrderStatusSubscriber type
type OrderStatusSubscriber struct {
	mock.Mock
}

// SubscribeOrderStatus provides a mock function with given fields: ctx, orderID
func (_m *OrderStatusSubscriber) SubscribeOrderStatus(ctx context.Context, orderID uuid.UUID) (<-chan model.OrderStatus, *errs.CustomError) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOrderStatus")
	}

	var r0 <-chan model.OrderStatus
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (<-chan model.OrderStatus, *errs.CustomError)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) <-chan model.OrderStatus); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.OrderStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) *errs.CustomError); ok {
		r1 = rf(ctx, orderID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// NewOrderStatusSubscriber creates a new instance of OrderStatusSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderStatusSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderStatusSubscriber {
	mock := &OrderStatusSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
