// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	errs "github.com/erdedan1/shared/errs"
	mock "github.com/stretchr/testify/mock"

	model "OrderService/internal/model"

	uuid "github.com/google/uuid"
)

// OrderStatusPublisher is an autogenerated mock type for the OrderStatusPublisher type
type OrderStatusPublisher struct {
	mock.Mock
}

// PublishOrderStatus provides a mock function with given fields: ctx, orderID, status
func (_m *OrderStatusPublisher) PublishOrderStatus(ctx context.Context, orderID uuid.UUID, status model.OrderStatus) *errs.CustomError {
	ret := _m.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderStatus")
	}

	var r0 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderStatus) *errs.CustomError); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errs.CustomError)
		}
	}

	return r0
}

// NewOrderStatusPublisher creates a new instance of OrderStatusPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderStatusPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderStatusPublisher {
	mock := &OrderStatusPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
