// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	errs "github.com/erdedan1/shared/errs"
	mock "github.com/stretchr/testify/mock"

	model "OrderService/internal/model"

	uuid "github.com/google/uuid"
)

// OrderRepo is an autogenerated mock type for the OrderRepo type
type OrderRepo struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepo) CreateOrder(ctx context.Context, order *model.Order) (*model.Order, *errs.CustomError) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) (*model.Order, *errs.CustomError)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) *model.Order); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Order) *errs.CustomError); ok {
		r1 = rf(ctx, order)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *OrderRepo) GetOrder(ctx context.Context, id uuid.UUID) (*model.Order, *errs.CustomError) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, *errs.CustomError)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) *errs.CustomError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// UpdateOrderStatus provides a mock function with given fields: ctx, id, order
func (_m *OrderRepo) UpdateOrderStatus(ctx context.Context, id uuid.UUID, order model.OrderStatus) *errs.CustomError {
	ret := _m.Called(ctx, id, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderStatus) *errs.CustomError); ok {
		r0 = rf(ctx, id, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errs.CustomError)
		}
	}

	return r0
}

// NewOrderRepo creates a new instance of OrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepo {
	mock := &OrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
