// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	errs "github.com/erdedan1/shared/errs"
	mock "github.com/stretchr/testify/mock"

	usecase "OrderService/internal/usecase"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, request
func (_m *OrderService) CreateOrder(ctx context.Context, request *usecase.CreateOrderInput) (*usecase.CreateOrderOutput, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *usecase.CreateOrderOutput
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.CreateOrderInput) (*usecase.CreateOrderOutput, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.CreateOrderInput) *usecase.CreateOrderOutput); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.CreateOrderOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.CreateOrderInput) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// GetOrderStatus provides a mock function with given fields: ctx, request
func (_m *OrderService) GetOrderStatus(ctx context.Context, request *usecase.GetOrderStatusInput) (*usecase.GetOrderStatusOutput, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 *usecase.GetOrderStatusOutput
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.GetOrderStatusInput) (*usecase.GetOrderStatusOutput, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.GetOrderStatusInput) *usecase.GetOrderStatusOutput); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.GetOrderStatusOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.GetOrderStatusInput) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// SubscribeOrderStatus provides a mock function with given fields: ctx, request
func (_m *OrderService) SubscribeOrderStatus(ctx context.Context, request *usecase.GetOrderStatusInput) (<-chan *usecase.GetOrderStatusOutput, *errs.CustomError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeOrderStatus")
	}

	var r0 <-chan *usecase.GetOrderStatusOutput
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.GetOrderStatusInput) (<-chan *usecase.GetOrderStatusOutput, *errs.CustomError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.GetOrderStatusInput) <-chan *usecase.GetOrderStatusOutput); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *usecase.GetOrderStatusOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.GetOrderStatusInput) *errs.CustomError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
