// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	errs "github.com/erdedan1/shared/errs"
	mock "github.com/stretchr/testify/mock"

	model "OrderService/internal/model"

	uuid "github.com/google/uuid"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserRepo) CreateUser(ctx context.Context, user model.User) {
	_m.Called(ctx, user)
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *UserRepo) GetUserById(ctx context.Context, id uuid.UUID) (*model.User, *errs.CustomError) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *model.User
	var r1 *errs.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, *errs.CustomError)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) *errs.CustomError); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.CustomError)
		}
	}

	return r0, r1
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
